### PR TITLE
Fix the M movement. It was hard coded to go to the 12th line. 

### PR DESCRIPTION
**Pull request by pmarin**
Moves the cursor to the middle line on the screen, at the first non-white position on the line.

### CODE REVIEW

**Comment by Orc** [comment]
Why not count = LINES/2 ?

**Comment by pmarin** [comment]
Because in Vi, Vim and Nvi  it will go to the middle of the lines that you see in the screen. 
For example if you have only 3 lines Vi will move to the second line.
If you go to LINES/2 you can end outside of the buffer.

**Comment by pmarin** [comment]
LINES is the number of lines on the screen.

**Comment by Orc** [comment]
Aha, right, got it.  Shows how often I've used the M command over the past ~40 years :-)

I'm not going to use your patch, though, because I can calculate the # of lines of content on the screen every time I do a `refresh()` (since I'm already walking the buffer to do the display I know what line# I'm at when I run out of content to display.)

I'll push my changes rn.

**Pull request closed without merging**
